spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:create_service_schema.sql
  liquibase:
    default-schema: service_schema
    change-log: classpath:db-changelog/main-changelog.xml

  level:
    web: debug

jwt:
  secret: dE567g8gHjh1kUIol0ovzWpo85hUIhhCF13gbnOPPm5vtI9784gvf56shk
  expiration: 2592000000

frontend:
  http: http://localhost:5173